// Test: SVG feature shape validation warnings.
include <../../../release/lib/boardgame_insert_toolkit_lib.4.scad>;

data = [
    [ G_PRINT_TYPES, BOX ],
    [ OBJECT_BOX,
        [ NAME, "svg validation" ],
        [ BOX_SIZE_XYZ, [120, 48, 18] ],
        [ BOX_NO_LID_B, true ],
        [ BOX_FEATURE,
            [ FTR_SHAPE, [ SVG ] ],
            [ FTR_COMPARTMENT_SIZE_XYZ, [24, 24, 14] ],
            [ POSITION_XY, [4, CENTER] ],
        ],
        [ BOX_FEATURE,
            [ FTR_SHAPE,
              [ SVG,
                [ SVG_FILE, "../assets/meeple.svg" ],
                [ SVG_WIDTH_MM, -10 ],
                [ SVG_CLEARANCE_MM, -0.2 ],
              ],
            ],
            [ FTR_COMPARTMENT_SIZE_XYZ, [24, 24, 14] ],
            [ POSITION_XY, [CENTER, CENTER] ],
        ],
        [ BOX_FEATURE,
            [ FTR_SHAPE,
              [ SVG,
                [ SVG_FILE, "../assets/meeple.svg" ],
                [ SVG_WIDTH_MM, 20 ],
                [ SVG_CLEARANCE_MM, 1 ],
              ],
            ],
            [ CHAMFER_N, 1.2 ],
            [ FTR_COMPARTMENT_SIZE_XYZ, [18, 18, 14] ],
            [ POSITION_XY, [MAX, CENTER] ],
        ],
    ],
];
Make(data);
