// Test: key/type and physical validation for divider rail-groove parameters.
include <../../../release/lib/boardgame_insert_toolkit_lib.4.scad>;

data = [
    [ G_PRINT_LID_B, false ],
    [ G_PRINT_BOX_B, false ],
    [ G_PRINT_DIVIDERS, ["wrong nested divider types", 7] ],
    [ G_PRINT_DIVIDERS_ONLY_B, "yes" ],
    [ G_ISOLATED_PRINT_BOX, "" ],
    [ G_VALIDATE_KEYS_B, true ],
    [ G_VALIDATE_PHYSICAL_B, true ],

    [ OBJECT_BOX,
        [ NAME, "malformed divider rail groove params" ],
        [ BOX_SIZE_XYZ, [36, 36, 12] ],
        [ BOX_NO_LID_B, true ],
        [ BOX_FEATURE,
            [ NAME, "wrong rail groove types" ],
            [ FTR_COMPARTMENT_SIZE_XYZ, [30, 30, 8] ],
            [ FTR_DIVIDERS,
                [ NAME, "wrong nested divider types" ],
                [ DIV_NUM_DIVIDERS, "many" ],
                [ DIV_AXIS, "z" ],
                [ DIV_SLOT_DEPTH, [1] ],
                [ DIV_RAILS_B, "yes" ],
                [ DIV_THICKNESS, "thick" ],
                [ DIV_OUTPUT_ONLY_B, "yes" ],
                [ DIV_FRAME_SIZE_XY, [10, "bad"] ],
            ],
        ],
    ],

    [ OBJECT_BOX,
        [ NAME, "physically invalid divider rail grooves" ],
        [ BOX_SIZE_XYZ, [36, 36, 12] ],
        [ BOX_NO_LID_B, true ],
        [ BOX_WALL_THICKNESS, 2 ],
        [ BOX_FEATURE,
            [ NAME, "bad rail groove placement and projection" ],
            [ FTR_COMPARTMENT_SIZE_XYZ, [30, 30, 9] ],
            [ FTR_DIVIDERS,
                [ NAME, "bad physical nested dividers" ],
                [ DIV_NUM_DIVIDERS, 3 ],
                [ DIV_AXIS, Y ],
                [ DIV_SLOT_DEPTH, 16.0 ],
            ],
        ],
    ],

    [ OBJECT_BOX,
        [ NAME, "non-positive divider rail grooves" ],
        [ BOX_SIZE_XYZ, [36, 36, 12] ],
        [ BOX_NO_LID_B, true ],
        [ BOX_FEATURE,
            [ NAME, "bad rail groove dimensions" ],
            [ FTR_COMPARTMENT_SIZE_XYZ, [30, 30, 8] ],
            [ FTR_DIVIDERS,
                [ DIV_NUM_DIVIDERS, 1 ],
                [ DIV_THICKNESS, -1.0 ],
                [ DIV_SLOT_DEPTH, -0.5 ],
            ],
        ],
    ],
];

Make(data);
