// Test: Lid variants — pattern lid and solid lid
include <boardgame_insert_toolkit_lib.4.scad>;

data = [
    [ G_DEFAULT_FONT, "Liberation Sans:style=Regular" ],
    [ G_PRINT_LID_B, true ],
    [ G_PRINT_BOX_B, true ],
    [ G_ISOLATED_PRINT_BOX, "" ],
    [ OBJECT_BOX,
        [ NAME, "pattern lid" ],
        [ BOX_SIZE_XYZ, [50, 50, 20] ],
        [ BOX_FEATURE,
            [ FTR_COMPARTMENT_SIZE_XYZ, [46, 46, 18] ],
        ],
        [ BOX_LID,
            [ LID_INSET_B, t ],
            [ LID_PATTERN_RADIUS, 8 ],
            [ LABEL,
                [ LBL_TEXT, "PATTERN" ],
                [ LBL_FONT, "Arial:style=Bold" ],
                [ LBL_SIZE, 10 ],
                [ LBL_PLACEMENT, CENTER ],
            ],
        ],
    ],
    [ OBJECT_BOX,
        [ NAME, "solid lid" ],
        [ BOX_SIZE_XYZ, [50, 50, 20] ],
        [ BOX_FEATURE,
            [ FTR_COMPARTMENT_SIZE_XYZ, [46, 46, 18] ],
        ],
        [ BOX_LID,
            [ LID_SOLID_B, t ],
            [ LID_INSET_B, t ],
            [ LID_HEIGHT, 1.5 ],
        ],
    ],
];
Make(data);
