// Test: Integration — multiple boxes rendered together with different features
include <boardgame_insert_toolkit_lib.4.scad>;
data = [
    [ G_DEFAULT_FONT, "Liberation Sans:style=Regular" ],
    [ G_PRINT_LID_B, true ],
    [ G_PRINT_BOX_B, true ],
    [ G_ISOLATED_PRINT_BOX, "" ],
    [ OBJECT_BOX,
        [ NAME, "simple solid lid" ],
        [ BOX_SIZE_XYZ, [45, 45, 15] ],
        [ BOX_LID,
            [ LID_SOLID_B, t ],
            [ LID_INSET_B, t ],
            [ LID_HEIGHT, 1.5 ],
        ],
        [ BOX_FEATURE,
            [ FTR_COMPARTMENT_SIZE_XYZ, [42, 42, 13] ],
        ],
    ],
    [ OBJECT_BOX,
        [ NAME, "round compartments pattern lid" ],
        [ BOX_SIZE_XYZ, [60, 60, 20] ],
        [ BOX_LID,
            [ LID_INSET_B, t ],
            [ LID_PATTERN_RADIUS, 6 ],
            [ LABEL,
                [ LBL_TEXT, "COINS" ],
                [ LBL_PLACEMENT, CENTER ],
            ],
        ],
        [ BOX_FEATURE,
            [ FTR_NUM_COMPARTMENTS_XY, [2, 2] ],
            [ FTR_COMPARTMENT_SIZE_XYZ, [25, 25, 18] ],
            [ FTR_SHAPE, ROUND ],
        ],
    ],
    [ OBJECT_BOX,
        [ NAME, "fillet with cutouts" ],
        [ BOX_SIZE_XYZ, [50, 80, 15] ],
        [ BOX_LID,
            [ LID_SOLID_B, t ],
            [ LID_INSET_B, t ],
            [ LID_HEIGHT, 1.5 ],
        ],
        [ BOX_FEATURE,
            [ FTR_NUM_COMPARTMENTS_XY, [1, 3] ],
            [ FTR_COMPARTMENT_SIZE_XYZ, [46, 22, 10] ],
            [ FTR_SHAPE, FILLET ],
            [ FTR_CUTOUT_SIDES_4B, [t, t, f, f] ],
        ],
    ],
];
Make(data);
