// Test: fitted divider rails and generated divider panels across compartment variants.
include <../../../release/lib/boardgame_insert_toolkit_lib.4.scad>;

data = [
    [ G_PRINT_LID_B, false ],
    [ G_PRINT_BOX_B, true ],
    [ G_ISOLATED_PRINT_BOX, "" ],

    [ OBJECT_BOX,
        [ NAME, "square fitted divider compartment" ],
        [ BOX_SIZE_XYZ, [66, 56, 24] ],
        [ BOX_NO_LID_B, true ],
        [ BOX_FEATURE,
            [ NAME, "square with x and y divider slots" ],
            [ FTR_COMPARTMENT_SIZE_XYZ, [58, 48, 18] ],
            [ FTR_DIVIDERS,
                [ NAME, "square fitted dividers" ],
                [ DIV_NUM_DIVIDERS, 2 ],
                [ DIV_AXIS, X ],
                [ DIV_THICKNESS, 1.0 ],
                [ DIV_SLOT_DEPTH, 2.0 ],
                [ DIV_TAB_TEXT, ["X1", "X2", "Y1"] ],
                [ DIV_TAB_SIZE_XY, [18, 7] ],
                [ DIV_TAB_CYCLE, 3 ],
                [ DIV_FRAME_TOP, 4 ],
                [ DIV_FRAME_BOTTOM, 3 ],
                [ DIV_FRAME_COLUMN, 3 ],
                [ DIV_FRAME_RADIUS, 2 ],
                [ DIV_FRAME_NUM_COLUMNS, 1 ],
            ],
        ],
    ],

    [ OBJECT_BOX,
        [ NAME, "repeated default clearance divider compartments" ],
        [ BOX_SIZE_XYZ, [72, 54, 22] ],
        [ BOX_NO_LID_B, true ],
        [ BOX_FEATURE,
            [ NAME, "two repeated compartments" ],
            [ FTR_NUM_COMPARTMENTS_XY, [2, 1] ],
            [ FTR_COMPARTMENT_SIZE_XYZ, [28, 42, 16] ],
            [ FTR_PADDING_XY, [4, 0] ],
            [ FTR_DIVIDERS,
                [ NAME, "one x slot per repeated compartment" ],
                [ DIV_NUM_DIVIDERS, 1 ],
                [ DIV_THICKNESS, 0.8 ],
                [ DIV_SLOT_DEPTH, 1.4 ],
                [ DIV_TAB_TEXT, ["R1", "R2"] ],
                [ DIV_TAB_SIZE_XY, [16, 6] ],
                [ DIV_TAB_CYCLE, 2 ],
                [ DIV_FRAME_TOP, 3 ],
                [ DIV_FRAME_BOTTOM, 3 ],
                [ DIV_FRAME_COLUMN, 2.5 ],
                [ DIV_FRAME_RADIUS, 1.5 ],
                [ DIV_FRAME_NUM_COLUMNS, 0 ],
            ],
        ],
    ],

    [ OBJECT_BOX,
        [ NAME, "horizontal round divider source compartment" ],
        [ BOX_SIZE_XYZ, [38, 48, 20] ],
        [ BOX_NO_LID_B, true ],
        [ BOX_FEATURE,
            [ NAME, "round bottom profile source" ],
            [ FTR_COMPARTMENT_SIZE_XYZ, [30, 40, 14] ],
            [ FTR_SHAPE, ROUND ],
            [ FTR_SHAPE_ROTATED_B, true ],
            [ FTR_DIVIDERS,
                [ NAME, "round source rails" ],
                [ DIV_NUM_DIVIDERS, 1 ],
                [ DIV_THICKNESS, 1.0 ],
                [ DIV_SLOT_DEPTH, 1.6 ],
            ],
        ],
    ],

    [ OBJECT_BOX,
        [ NAME, "horizontal hex divider source compartment" ],
        [ BOX_SIZE_XYZ, [42, 52, 20] ],
        [ BOX_NO_LID_B, true ],
        [ BOX_FEATURE,
            [ NAME, "hex bottom profile source" ],
            [ FTR_COMPARTMENT_SIZE_XYZ, [34, 44, 14] ],
            [ FTR_SHAPE, HEX ],
            [ FTR_SHAPE_ROTATED_B, true ],
            [ FTR_DIVIDERS,
                [ NAME, "hex source rails" ],
                [ DIV_NUM_DIVIDERS, 1 ],
                [ DIV_THICKNESS, 1.0 ],
                [ DIV_SLOT_DEPTH, 1.6 ],
            ],
        ],
    ],

    [ OBJECT_BOX,
        [ NAME, "output only horizontal round dividers" ],
        [ BOX_SIZE_XYZ, [38, 48, 20] ],
        [ BOX_NO_LID_B, true ],
        [ BOX_FEATURE,
            [ NAME, "round bottom profile divider" ],
            [ FTR_COMPARTMENT_SIZE_XYZ, [30, 40, 14] ],
            [ FTR_SHAPE, ROUND ],
            [ FTR_SHAPE_ROTATED_B, true ],
            [ FTR_DIVIDERS,
                [ NAME, "generated round-bottom panel" ],
                [ DIV_OUTPUT_ONLY_B, true ],
                [ DIV_NUM_DIVIDERS, 1 ],
                [ DIV_THICKNESS, 1.0 ],
                [ DIV_SLOT_DEPTH, 1.6 ],
                [ DIV_TAB_TEXT, [""] ],
                [ DIV_TAB_TEXT_SIZE, 1 ],
                [ DIV_TAB_SIZE_XY, [12, 4] ],
                [ DIV_FRAME_NUM_COLUMNS, -1 ],
            ],
        ],
    ],

    [ OBJECT_BOX,
        [ NAME, "output only horizontal hex dividers" ],
        [ BOX_SIZE_XYZ, [42, 52, 20] ],
        [ BOX_NO_LID_B, true ],
        [ BOX_FEATURE,
            [ NAME, "hex bottom profile divider" ],
            [ FTR_COMPARTMENT_SIZE_XYZ, [34, 44, 14] ],
            [ FTR_SHAPE, HEX ],
            [ FTR_SHAPE_ROTATED_B, true ],
            [ FTR_DIVIDERS,
                [ NAME, "generated hex-bottom panel" ],
                [ DIV_OUTPUT_ONLY_B, true ],
                [ DIV_NUM_DIVIDERS, 1 ],
                [ DIV_THICKNESS, 1.0 ],
                [ DIV_SLOT_DEPTH, 1.6 ],
                [ DIV_TAB_TEXT, [""] ],
                [ DIV_TAB_TEXT_SIZE, 1 ],
                [ DIV_TAB_SIZE_XY, [12, 4] ],
                [ DIV_FRAME_NUM_COLUMNS, -1 ],
            ],
        ],
    ],
];

Make(data);
