// Test: LID_FRAME_WIDTH defaults and applies to patterned cap, inset, and sliding lids
include <../../../release/lib/boardgame_insert_toolkit_lib.4.scad>;

data = [
    [ G_PRINT_LID_B, true ],
    [ G_PRINT_BOX_B, false ],
    [ G_ISOLATED_PRINT_BOX, "" ],
    [ G_WALL_THICKNESS, 3 ],
    [ OBJECT_BOX,
        [ NAME, "cap default frame" ],
        [ BOX_SIZE_XYZ, [68, 48, 18] ],
        [ BOX_LID,
            [ LID_TYPE, LID_CAP ],
            [ LID_PATTERN_RADIUS, 4 ],
            [ LID_PATTERN_THICKNESS, 0.7 ],
        ],
        [ BOX_FEATURE,
            [ FTR_COMPARTMENT_SIZE_XYZ, [62, 42, 15] ],
        ],
    ],
    [ OBJECT_BOX,
        [ NAME, "inset default frame" ],
        [ BOX_SIZE_XYZ, [68, 48, 18] ],
        [ BOX_LID,
            [ LID_TYPE, LID_INSET ],
            [ LID_PATTERN_RADIUS, 4 ],
            [ LID_PATTERN_THICKNESS, 0.7 ],
        ],
        [ BOX_FEATURE,
            [ FTR_COMPARTMENT_SIZE_XYZ, [62, 42, 15] ],
        ],
    ],
    [ OBJECT_BOX,
        [ NAME, "sliding default frame" ],
        [ BOX_SIZE_XYZ, [68, 48, 18] ],
        [ BOX_LID,
            [ LID_TYPE, LID_SLIDING ],
            [ LID_PATTERN_RADIUS, 4 ],
            [ LID_PATTERN_THICKNESS, 0.7 ],
        ],
        [ BOX_FEATURE,
            [ FTR_COMPARTMENT_SIZE_XYZ, [62, 42, 15] ],
        ],
    ],
    [ OBJECT_BOX,
        [ NAME, "solid ignores frame" ],
        [ BOX_SIZE_XYZ, [68, 48, 18] ],
        [ BOX_LID,
            [ LID_TYPE, LID_CAP ],
            [ LID_SOLID_B, true ],
            [ LID_FRAME_WIDTH, 6 ],
        ],
        [ BOX_FEATURE,
            [ FTR_COMPARTMENT_SIZE_XYZ, [62, 42, 15] ],
        ],
    ],
];
Make(data);
