// Test: FILLET compartment shape — normal, rotated, with custom fillet radius
include <../../../release/lib/boardgame_insert_toolkit_lib.4.scad>;

data = [
    [ G_PRINT_TYPES, [ BOX, DIVIDERS ] ],
    [ OBJECT_BOX,
        [ NAME, "fillet normal" ],
        [ BOX_SIZE_XYZ, [50, 50, 20] ],
        [ BOX_FEATURE,
            [ FTR_NUM_COMPARTMENTS_XY, [2, 2] ],
            [ FTR_COMPARTMENT_SIZE_XYZ, [20, 20, 18] ],
            [ FTR_SHAPE, FILLET ],
        ],
    ],
    [ OBJECT_BOX,
        [ NAME, "fillet rotated" ],
        [ BOX_SIZE_XYZ, [50, 50, 20] ],
        [ BOX_FEATURE,
            [ FTR_NUM_COMPARTMENTS_XY, [2, 2] ],
            [ FTR_COMPARTMENT_SIZE_XYZ, [20, 20, 18] ],
            [ FTR_SHAPE, FILLET ],
            [ FTR_SHAPE_AXIS, X ],
        ],
    ],
    [ OBJECT_BOX,
        [ NAME, "fillet custom radius" ],
        [ BOX_SIZE_XYZ, [50, 50, 20] ],
        [ BOX_FEATURE,
            [ FTR_NUM_COMPARTMENTS_XY, [2, 2] ],
            [ FTR_COMPARTMENT_SIZE_XYZ, [20, 20, 18] ],
            [ FTR_SHAPE, FILLET ],
            [ FTR_FILLET_RADIUS, 8 ],
        ],
    ],
];
Make(data);
