// Test: Physical validation messages for fit and printability issues
include <../../../release/lib/boardgame_insert_toolkit_lib.4.scad>;

data = [
    [ G_PRINT_LID_B, true ],
    [ G_PRINT_BOX_B, false ],
    [ G_ISOLATED_PRINT_BOX, "" ],
    [ OBJECT_BOX,
        [ NAME, "physical validation box" ],
        [ BOX_SIZE_XYZ, [50, 40, 12] ],
        [ BOX_NO_LID_B, true ],
        [ BOX_WALL_THICKNESS, 0.6 ],
        [ BOX_LID,
            [ LID_PATTERN_THICKNESS, 0.2 ],
            [ LID_FRAME_WIDTH, 0.2 ],
        ],
        [ BOX_FEATURE,
            [ NAME, "too tall and overlapping" ],
            [ FTR_COMPARTMENT_SIZE_XYZ, [30, 28, 12] ],
            [ POSITION_XY, [0, 0] ],
        ],
        [ BOX_FEATURE,
            [ NAME, "out of bounds and overlapping" ],
            [ FTR_COMPARTMENT_SIZE_XYZ, [30, 28, 8] ],
            [ POSITION_XY, [20, 0] ],
        ],
    ],
    [ OBJECT_BOX,
        [ NAME, "cutout invalid percentages" ],
        [ BOX_SIZE_XYZ, [35, 35, 12] ],
        [ BOX_NO_LID_B, true ],
        [ BOX_FEATURE,
            [ NAME, "invalid side cutout params" ],
            [ FTR_COMPARTMENT_SIZE_XYZ, [30, 30, 8] ],
            [ FTR_CUTOUT_SIDES_4B, [true, false, false, false] ],
            [ FTR_CUTOUT_HEIGHT_PCT, 125 ],
            [ FTR_CUTOUT_DEPTH_PCT, -10 ],
            [ FTR_CUTOUT_WIDTH_PCT, 110 ],
            [ FTR_CUTOUT_DEPTH_MAX, -2 ],
        ],
    ],
    [ OBJECT_BOX,
        [ NAME, "fragile side cutout" ],
        [ BOX_SIZE_XYZ, [40, 30, 12] ],
        [ BOX_NO_LID_B, true ],
        [ BOX_FEATURE,
            [ NAME, "fragile front cutout" ],
            [ FTR_COMPARTMENT_SIZE_XYZ, [36, 26, 9] ],
            [ FTR_CUTOUT_SIDES_4B, [true, false, false, false] ],
            [ FTR_CUTOUT_HEIGHT_PCT, 96 ],
            [ FTR_CUTOUT_DEPTH_PCT, 99 ],
            [ FTR_CUTOUT_WIDTH_PCT, 98 ],
        ],
    ],
    [ OBJECT_BOX,
        [ NAME, "fragile rounded side cutout" ],
        [ BOX_SIZE_XYZ, [24, 24, 20] ],
        [ BOX_NO_LID_B, true ],
        [ BOX_FEATURE,
            [ NAME, "narrow rounded-bottom finger cutout" ],
            [ FTR_COMPARTMENT_SIZE_XYZ, [14, 18, 18] ],
            [ FTR_CUTOUT_SIDES_4B, [true, false, false, false] ],
            [ FTR_CUTOUT_HEIGHT_PCT, 20 ],
            [ FTR_CUTOUT_WIDTH_PCT, 30 ],
        ],
    ],
    [ OBJECT_BOX,
        [ NAME, "fragile standard rounded cutout" ],
        [ BOX_SIZE_XYZ, [24, 24, 14] ],
        [ BOX_NO_LID_B, true ],
        [ BOX_FEATURE,
            [ NAME, "shallow rounded side cutout" ],
            [ FTR_COMPARTMENT_SIZE_XYZ, [18, 18, 10] ],
            [ FTR_CUTOUT_SIDES_4B, [true, false, false, false] ],
            [ FTR_CUTOUT_HEIGHT_PCT, 100 ],
            [ FTR_CUTOUT_DEPTH_PCT, 10 ],
        ],
    ],
    [ OBJECT_BOX,
        [ NAME, "fragile bottom cutout" ],
        [ BOX_SIZE_XYZ, [32, 32, 10] ],
        [ BOX_NO_LID_B, true ],
        [ BOX_WALL_THICKNESS, 1.5 ],
        [ BOX_FEATURE,
            [ NAME, "thin floor cutout" ],
            [ FTR_COMPARTMENT_SIZE_XYZ, [28, 28, 8.2] ],
            [ FTR_CUTOUT_BOTTOM_B, true ],
            [ FTR_CUTOUT_BOTTOM_PCT, 98 ],
        ],
    ],
    [ OBJECT_BOX,
        [ NAME, "fragile corner cutout" ],
        [ BOX_SIZE_XYZ, [30, 30, 10] ],
        [ BOX_NO_LID_B, true ],
        [ BOX_FEATURE,
            [ NAME, "overlapping corner cutouts" ],
            [ FTR_COMPARTMENT_SIZE_XYZ, [4, 4, 8] ],
            [ FTR_PADDING_XY, [2, 2] ],
            [ FTR_CUTOUT_CORNERS_4B, [true, true, true, true] ],
        ],
    ],
    [ OBJECT_BOX,
        [ NAME, "fragile corner bridge" ],
        [ BOX_SIZE_XYZ, [8, 8, 5] ],
        [ BOX_NO_LID_B, true ],
        [ BOX_FEATURE,
            [ NAME, "tiny paired corner cutouts" ],
            [ FTR_COMPARTMENT_SIZE_XYZ, [0.6, 0.6, 2] ],
            [ FTR_PADDING_XY, [0, 0] ],
            [ FTR_CUTOUT_CORNERS_4B, [true, false, true, false] ],
        ],
    ],
    [ OBJECT_DIVIDERS,
        [ NAME, "thin divider" ],
        [ DIV_THICKNESS, 0.2 ],
        [ DIV_FRAME_SIZE_XY, [20, 12] ],
        [ DIV_TAB_TEXT, ["A", "B"] ],
    ],
    [ OBJECT_BOX,
        [ NAME, "render target" ],
        [ BOX_SIZE_XYZ, [20, 20, 8] ],
        [ BOX_LID,
            [ LID_SOLID_B, true ],
        ],
        [ BOX_FEATURE,
            [ FTR_COMPARTMENT_SIZE_XYZ, [16, 16, 6] ],
        ],
    ],
];

detent_thin_data = [
    [ G_PRINT_LID_B, false ],
    [ G_PRINT_BOX_B, false ],
    [ G_ISOLATED_PRINT_BOX, "" ],
    [ G_DETENT_THICKNESS, 0.2 ],
    [ G_DETENT_SPACING, 20 ],
    [ G_DETENT_DIST_FROM_CORNER, 0.1 ],
    [ OBJECT_BOX,
        [ NAME, "thin and too-close sliding detent" ],
        [ BOX_SIZE_XYZ, [20, 18, 8] ],
        [ BOX_WALL_THICKNESS, 1.0 ],
        [ BOX_LID,
            [ LID_TYPE, LID_SLIDING ],
            [ LID_SLIDE_SIDE, FRONT ],
            [ LID_SOLID_B, true ],
        ],
    ],
];

detent_collapsed_data = [
    [ G_PRINT_LID_B, false ],
    [ G_PRINT_BOX_B, false ],
    [ G_ISOLATED_PRINT_BOX, "" ],
    [ G_DETENT_THICKNESS, 0.8 ],
    [ G_DETENT_SPACING, 2 ],
    [ G_DETENT_DIST_FROM_CORNER, 9 ],
    [ OBJECT_BOX,
        [ NAME, "collapsed sliding detent" ],
        [ BOX_SIZE_XYZ, [18, 16, 8] ],
        [ BOX_WALL_THICKNESS, 1.0 ],
        [ BOX_LID,
            [ LID_TYPE, LID_SLIDING ],
            [ LID_SLIDE_SIDE, FRONT ],
            [ LID_SOLID_B, true ],
        ],
    ],
];

Make(data);
Make(detent_thin_data);
Make(detent_collapsed_data);
