// Test: Integration — labels on lid, all box sides, and per-compartment
include <boardgame_insert_toolkit_lib.4.scad>;

data = [
    [ G_PRINT_LID_B, true ],
    [ G_PRINT_BOX_B, true ],
    [ G_ISOLATED_PRINT_BOX, "" ],
    [ OBJECT_BOX,
        [ NAME, "labels everywhere" ],
        [ BOX_SIZE_XYZ, [60, 60, 20] ],
        [ BOX_LID,
            [ LID_PATTERN_RADIUS, 8 ],
            [ LABEL,
                [ LBL_TEXT, "TOP LABEL" ],
                [ LBL_SIZE, AUTO ],
            ],
        ],
        [ LABEL,
            [ LBL_TEXT, "FRONT" ],
            [ LBL_SIZE, AUTO ],
            [ LBL_PLACEMENT, FRONT ],
        ],
        [ LABEL,
            [ LBL_TEXT, "BACK" ],
            [ LBL_SIZE, AUTO ],
            [ LBL_PLACEMENT, BACK ],
        ],
        [ LABEL,
            [ LBL_TEXT, "LEFT" ],
            [ LBL_SIZE, AUTO ],
            [ LBL_PLACEMENT, LEFT ],
        ],
        [ LABEL,
            [ LBL_TEXT, "RIGHT" ],
            [ LBL_SIZE, AUTO ],
            [ LBL_PLACEMENT, RIGHT ],
        ],
        [ BOX_FEATURE,
            [ FTR_NUM_COMPARTMENTS_XY, [2, 2] ],
            [ FTR_COMPARTMENT_SIZE_XYZ, [20, 20, 5] ],
            [ FTR_PADDING_XY, [5, 5] ],
            [ LABEL,
                [ LBL_TEXT,
                    [
                        [ "A", "B" ],
                        [ "C", "D" ],
                    ]
                ],
                [ LBL_PLACEMENT, BACK ],
                [ LBL_SIZE, AUTO ],
            ],
        ],
    ],
];
Make(data);
