// Test: Physical footprint validation for rotated and sheared components
include <../../../release/lib/boardgame_insert_toolkit_lib.4.scad>;

data = [
    [ G_PRINT_LID_B, false ],
    [ G_PRINT_BOX_B, true ],
    [ G_ISOLATED_PRINT_BOX, "" ],
    [ OBJECT_BOX,
        [ NAME, "rotated in bounds" ],
        [ BOX_SIZE_XYZ, [40, 40, 8] ],
        [ BOX_NO_LID_B, true ],
        [ BOX_FEATURE,
            [ NAME, "rotated safe footprint" ],
            [ FTR_COMPARTMENT_SIZE_XYZ, [10, 20, 5] ],
            [ ROTATION, 45 ],
            [ POSITION_XY, [CENTER, CENTER] ],
        ],
    ],
    [ OBJECT_BOX,
        [ NAME, "rotated out of bounds" ],
        [ BOX_SIZE_XYZ, [30, 30, 8] ],
        [ BOX_NO_LID_B, true ],
        [ BOX_FEATURE,
            [ NAME, "rotated oversized footprint" ],
            [ FTR_COMPARTMENT_SIZE_XYZ, [10, 20, 5] ],
            [ ROTATION, 45 ],
            [ POSITION_XY, [0, 0] ],
        ],
    ],
    [ OBJECT_BOX,
        [ NAME, "sheared in bounds" ],
        [ BOX_SIZE_XYZ, [40, 30, 8] ],
        [ BOX_NO_LID_B, true ],
        [ BOX_FEATURE,
            [ NAME, "sheared safe footprint" ],
            [ FTR_COMPARTMENT_SIZE_XYZ, [10, 12, 4] ],
            [ FTR_SHEAR, [30, 0] ],
            [ POSITION_XY, [10, 8] ],
        ],
    ],
    [ OBJECT_BOX,
        [ NAME, "sheared out of bounds" ],
        [ BOX_SIZE_XYZ, [26, 20, 8] ],
        [ BOX_NO_LID_B, true ],
        [ BOX_FEATURE,
            [ NAME, "sheared oversized footprint" ],
            [ FTR_COMPARTMENT_SIZE_XYZ, [10, 12, 6] ],
            [ FTR_SHEAR, [45, 0] ],
            [ POSITION_XY, [0, 0] ],
        ],
    ],
    [ OBJECT_BOX,
        [ NAME, "transformed overlap" ],
        [ BOX_SIZE_XYZ, [50, 30, 8] ],
        [ BOX_NO_LID_B, true ],
        [ BOX_FEATURE,
            [ NAME, "rotated overlap candidate" ],
            [ FTR_COMPARTMENT_SIZE_XYZ, [20, 6, 4] ],
            [ ROTATION, 30 ],
            [ POSITION_XY, [5, 10] ],
        ],
        [ BOX_FEATURE,
            [ NAME, "raw touching candidate" ],
            [ FTR_COMPARTMENT_SIZE_XYZ, [10, 6, 4] ],
            [ POSITION_XY, [25, 10] ],
        ],
    ],
];

Make(data);
