// Test: Compartment padding — FTR_PADDING_XY and FTR_PADDING_HEIGHT_ADJUST_XY
include <boardgame_insert_toolkit_lib.4.scad>;

data = [
    [ G_PRINT_LID_B, false ],
    [ G_PRINT_BOX_B, true ],
    [ G_ISOLATED_PRINT_BOX, "" ],
    [ OBJECT_BOX,
        [ NAME, "large padding" ],
        [ BOX_SIZE_XYZ, [80, 80, 20] ],
        [ BOX_FEATURE,
            [ FTR_NUM_COMPARTMENTS_XY, [2, 2] ],
            [ FTR_COMPARTMENT_SIZE_XYZ, [20, 20, 18] ],
            [ FTR_PADDING_XY, [10, 10] ],
        ],
    ],
    [ OBJECT_BOX,
        [ NAME, "asymmetric padding" ],
        [ BOX_SIZE_XYZ, [80, 80, 20] ],
        [ BOX_FEATURE,
            [ FTR_NUM_COMPARTMENTS_XY, [2, 2] ],
            [ FTR_COMPARTMENT_SIZE_XYZ, [20, 20, 18] ],
            [ FTR_PADDING_XY, [15, 5] ],
        ],
    ],
    [ OBJECT_BOX,
        [ NAME, "padding height adjust" ],
        [ BOX_SIZE_XYZ, [80, 80, 20] ],
        [ BOX_FEATURE,
            [ FTR_NUM_COMPARTMENTS_XY, [2, 2] ],
            [ FTR_COMPARTMENT_SIZE_XYZ, [20, 20, 18] ],
            [ FTR_PADDING_XY, [10, 10] ],
            [ FTR_PADDING_HEIGHT_ADJUST_XY, [-5, -10] ],
        ],
    ],
];
Make(data);
