// Test: FTR_DIVIDERS layout-generated divider centerlines from bay sizes.
include <../../../release/lib/boardgame_insert_toolkit_lib.4.scad>;

data = [
    [ G_PRINT_LID_B, false ],
    [ G_PRINT_BOX_B, true ],
    [ G_ISOLATED_PRINT_BOX, "" ],

    [ OBJECT_BOX,
        [ NAME, "x-axis bay layout dividers" ],
        [ BOX_SIZE_XYZ, [88, 52, 22] ],
        [ BOX_NO_LID_B, true ],
        [ BOX_FEATURE,
            [ NAME, "three deck lanes along x" ],
            [ FTR_COMPARTMENT_SIZE_XYZ, [78, 40, 16] ],
            [ FTR_DIVIDERS,
                [ NAME, "x layout dividers" ],
                [ DIV_AXIS, X ],
                [ DIV_LAYOUT_BAYS, 3 ],
                [ DIV_LAYOUT_BAY_SIZE, 20 ],
                [ DIV_THICKNESS, 1.0 ],
                [ DIV_RAIL_SIZE_XYZ, [1, 1.5, 16] ],
                [ DIV_TAB_TEXT, ["", "", ""] ],
                [ DIV_TAB_SIZE_XY, [0.4, 1.0] ],
                [ DIV_FRAME_NUM_COLUMNS, -1 ],
            ],
        ],
    ],

    [ OBJECT_BOX,
        [ NAME, "y-axis bay layout dividers" ],
        [ BOX_SIZE_XYZ, [52, 94, 22] ],
        [ BOX_NO_LID_B, true ],
        [ BOX_FEATURE,
            [ NAME, "four token lanes along y" ],
            [ FTR_COMPARTMENT_SIZE_XYZ, [40, 84, 16] ],
            [ FTR_DIVIDERS,
                [ NAME, "y layout dividers" ],
                [ DIV_AXIS, Y ],
                [ DIV_LAYOUT_BAYS, 4 ],
                [ DIV_LAYOUT_BAY_SIZE, 0 ],
                [ DIV_THICKNESS, 0.8 ],
                [ DIV_RAIL_SIZE_XYZ, [1, 1.4, 16] ],
                [ DIV_TAB_TEXT, ["", "", ""] ],
                [ DIV_TAB_SIZE_XY, [0.4, 1.0] ],
                [ DIV_FRAME_NUM_COLUMNS, 1 ],
            ],
        ],
    ],

    [ OBJECT_BOX,
        [ NAME, "repeated bay layout dividers" ],
        [ BOX_SIZE_XYZ, [96, 48, 20] ],
        [ BOX_NO_LID_B, true ],
        [ BOX_FEATURE,
            [ NAME, "three repeated two-lane compartments" ],
            [ FTR_NUM_COMPARTMENTS_XY, [3, 1] ],
            [ FTR_COMPARTMENT_SIZE_XYZ, [26, 36, 14] ],
            [ FTR_PADDING_XY, [3, 0] ],
            [ FTR_DIVIDERS,
                [ NAME, "repeated layout dividers" ],
                [ DIV_AXIS, X ],
                [ DIV_LAYOUT_BAYS, 2 ],
                [ DIV_LAYOUT_BAY_SIZE, 10 ],
                [ DIV_THICKNESS, 1.0 ],
                [ DIV_RAIL_SIZE_XYZ, [1, 1.2, 14] ],
                [ DIV_TAB_TEXT, ["", "", ""] ],
                [ DIV_TAB_SIZE_XY, [0.4, 1.0] ],
                [ DIV_TAB_CYCLE, 3 ],
                [ DIV_FRAME_NUM_COLUMNS, -1 ],
            ],
        ],
    ],
];

Make(data);
