// Test: fitted divider rails and generated divider panels across compartment variants.
include <../../../release/lib/boardgame_insert_toolkit_lib.4.scad>;

data = [
    [ G_PRINT_LID_B, false ],
    [ G_PRINT_BOX_B, true ],
    [ G_ISOLATED_PRINT_BOX, "" ],

    [ OBJECT_BOX,
        [ NAME, "square fitted divider compartment" ],
        [ BOX_SIZE_XYZ, [66, 56, 24] ],
        [ BOX_NO_LID_B, true ],
        [ BOX_FEATURE,
            [ NAME, "square with x and y divider slots" ],
            [ FTR_COMPARTMENT_SIZE_XYZ, [58, 48, 18] ],
            [ FTR_DIVIDERS,
                [ NAME, "square fitted dividers" ],
                [ DIV_AXIS, X ],
                [ DIV_LAYOUT_BAYS, 3 ],
                [ DIV_LAYOUT_BAY_SIZE, 0 ],
                [ DIV_THICKNESS, 1.0 ],
                [ DIV_RAIL_SIZE_XYZ, [1, 2.0, 18] ],
                [ DIV_TAB_TEXT, ["X1", "X2", "Y1"] ],
                [ DIV_TAB_SIZE_XY, [18, 7] ],
                [ DIV_TAB_CYCLE, 3 ],
                [ DIV_FRAME_TOP, 4 ],
                [ DIV_FRAME_BOTTOM, 3 ],
                [ DIV_FRAME_COLUMN, 3 ],
                [ DIV_FRAME_RADIUS, 2 ],
                [ DIV_FRAME_NUM_COLUMNS, 1 ],
            ],
        ],
    ],

    [ OBJECT_BOX,
        [ NAME, "horizontal round divider source compartment" ],
        [ BOX_SIZE_XYZ, [38, 48, 20] ],
        [ BOX_NO_LID_B, true ],
        [ BOX_FEATURE,
            [ NAME, "round bottom profile source" ],
            [ FTR_COMPARTMENT_SIZE_XYZ, [30, 40, 14] ],
            [ FTR_SHAPE, ROUND ],
            [ FTR_SHAPE_AXIS, X ],
            [ FTR_DIVIDERS,
                [ NAME, "round source rails" ],
                [ DIV_LAYOUT_BAYS, 2 ],
                [ DIV_LAYOUT_BAY_SIZE, 0 ],
                [ DIV_THICKNESS, 1.0 ],
                [ DIV_RAIL_SIZE_XYZ, [1, 1.6, 14] ],
                [ DIV_TAB_SIZE_XY, [0.4, 1.0] ],
                [ DIV_FRAME_NUM_COLUMNS, -1 ],
            ],
        ],
    ],

    [ OBJECT_BOX,
        [ NAME, "horizontal hex divider source compartment" ],
        [ BOX_SIZE_XYZ, [42, 52, 20] ],
        [ BOX_NO_LID_B, true ],
        [ BOX_FEATURE,
            [ NAME, "hex bottom profile source" ],
            [ FTR_COMPARTMENT_SIZE_XYZ, [34, 44, 14] ],
            [ FTR_SHAPE, HEX ],
            [ FTR_SHAPE_AXIS, X ],
            [ FTR_DIVIDERS,
                [ NAME, "hex source rails" ],
                [ DIV_LAYOUT_BAYS, 2 ],
                [ DIV_LAYOUT_BAY_SIZE, 0 ],
                [ DIV_THICKNESS, 1.0 ],
                [ DIV_RAIL_SIZE_XYZ, [1, 1.6, 14] ],
                [ DIV_TAB_SIZE_XY, [0.4, 1.0] ],
                [ DIV_FRAME_NUM_COLUMNS, -1 ],
            ],
        ],
    ],
];

Make(data);
