// Test: compartment-local divider side-wall rail grooves inside BOX_FEATURE.
include <../../../release/lib/boardgame_insert_toolkit_lib.4.scad>;

data = [
    [ G_PRINT_LID_B, false ],
    [ G_PRINT_BOX_B, true ],
    [ G_PRINT_DIVIDERS, false ],
    [ G_ISOLATED_PRINT_BOX, "" ],

    [ OBJECT_BOX,
        [ NAME, "divider rail groove card tray" ],
        [ BOX_SIZE_XYZ, [72, 97, 32] ],
        [ BOX_NO_LID_B, true ],
        [ BOX_FEATURE,
            [ NAME, "x-axis divider rail grooves" ],
            [ FTR_COMPARTMENT_SIZE_XYZ, [66, 91, 27] ],
            [ FTR_DIVIDERS,
                [ NAME, "matching loose dividers" ],
                [ DIV_AXIS, X ],
                [ DIV_LAYOUT_BAYS, 3 ],
                [ DIV_LAYOUT_BAY_SIZE, 0 ],
                [ DIV_THICKNESS, 0.8 ],
                [ DIV_RAIL_SIZE_XYZ, [1, 1.5, 27] ],
            ],
            [ FTR_CUTOUT_SIDES_4B, [true, false, false, false] ],
            [ FTR_CUTOUT_HEIGHT_PCT, 45 ],
            [ FTR_CUTOUT_DEPTH_PCT, 18 ],
            [ FTR_CUTOUT_WIDTH_PCT, 42 ],
        ],
    ],

    [ OBJECT_BOX,
        [ NAME, "divider panels without box rails" ],
        [ BOX_SIZE_XYZ, [62, 46, 22] ],
        [ BOX_NO_LID_B, true ],
        [ BOX_FEATURE,
            [ NAME, "rail disabled compartment" ],
            [ FTR_COMPARTMENT_SIZE_XYZ, [54, 38, 16] ],
            [ FTR_DIVIDERS,
                [ NAME, "rail disabled dividers" ],
                [ DIV_NO_RAILS_B, true ],
                [ DIV_LAYOUT_BAYS, 3 ],
                [ DIV_LAYOUT_BAY_SIZE, 0 ],
                [ DIV_THICKNESS, 1.0 ],
            ],
        ],
    ],
];

Make(data);
