// Test: OCT2 compartment shape (rotated octagon) — normal, rotated, vertical
include <../../../release/lib/boardgame_insert_toolkit_lib.4.scad>;

data = [
    [ G_PRINT_TYPES, [ BOX, DIVIDERS ] ],
    [ OBJECT_BOX,
        [ NAME, "oct2 normal" ],
        [ BOX_SIZE_XYZ, [50, 50, 20] ],
        [ BOX_FEATURE,
            [ FTR_NUM_COMPARTMENTS_XY, [2, 2] ],
            [ FTR_COMPARTMENT_SIZE_XYZ, [20, 20, 18] ],
            [ FTR_SHAPE, OCT2 ],
        ],
    ],
    [ OBJECT_BOX,
        [ NAME, "oct2 rotated" ],
        [ BOX_SIZE_XYZ, [50, 50, 20] ],
        [ BOX_FEATURE,
            [ FTR_NUM_COMPARTMENTS_XY, [2, 2] ],
            [ FTR_COMPARTMENT_SIZE_XYZ, [20, 20, 18] ],
            [ FTR_SHAPE, OCT2 ],
            [ FTR_SHAPE_AXIS, X ],
        ],
    ],
    [ OBJECT_BOX,
        [ NAME, "oct2 vertical" ],
        [ BOX_SIZE_XYZ, [50, 50, 20] ],
        [ BOX_FEATURE,
            [ FTR_NUM_COMPARTMENTS_XY, [2, 2] ],
            [ FTR_COMPARTMENT_SIZE_XYZ, [20, 20, 18] ],
            [ FTR_SHAPE, OCT2 ],
            [ FTR_SHAPE_VERTICAL_B, t ],
        ],
    ],
];
Make(data);
