// Test: compartment-local divider side-wall rail grooves inside BOX_FEATURE.
include <../../../release/lib/boardgame_insert_toolkit_lib.4.scad>;

data = [
    [ G_PRINT_LID_B, false ],
    [ G_PRINT_BOX_B, true ],
    [ G_ISOLATED_PRINT_BOX, "" ],

    [ OBJECT_BOX,
        [ NAME, "divider rail groove card tray" ],
        [ BOX_SIZE_XYZ, [72, 97, 32] ],
        [ BOX_NO_LID_B, true ],
        [ BOX_FEATURE,
            [ NAME, "x-axis divider rail grooves" ],
            [ FTR_COMPARTMENT_SIZE_XYZ, [66, 91, 27] ],
            [ FTR_DIVIDERS,
                [ NAME, "matching loose dividers" ],
                [ DIV_NUM_DIVIDERS, 2 ],
                [ DIV_AXIS, X ],
                [ DIV_THICKNESS, 0.8 ],
                [ DIV_SLOT_DEPTH, 1.5 ],
                [ DIV_TAB_TEXT, ["A", "B", "C"] ],
                [ DIV_FRAME_SIZE_XY, [91, 20] ],
            ],
            [ FTR_CUTOUT_SIDES_4B, [true, false, false, false] ],
            [ FTR_CUTOUT_HEIGHT_PCT, 45 ],
            [ FTR_CUTOUT_DEPTH_PCT, 18 ],
            [ FTR_CUTOUT_WIDTH_PCT, 42 ],
        ],
    ],

    [ OBJECT_BOX,
        [ NAME, "transformed divider rail groove tray" ],
        [ BOX_SIZE_XYZ, [82, 74, 28] ],
        [ BOX_NO_LID_B, true ],
        [ BOX_FEATURE,
            [ NAME, "rotated and sheared rail grooves" ],
            [ FTR_COMPARTMENT_SIZE_XYZ, [44, 58, 22] ],
            [ POSITION_XY, [16, 7] ],
            [ ROTATION, 8 ],
            [ FTR_SHEAR, [0.08, 0] ],
            [ FTR_DIVIDERS,
                [ NAME, "matching transformed dividers" ],
                [ DIV_NUM_DIVIDERS, 2 ],
                [ DIV_AXIS, Y ],
                [ DIV_THICKNESS, 1.0 ],
                [ DIV_SLOT_DEPTH, 1.4 ],
                [ DIV_TAB_SIZE_XY, [22, 8] ],
                [ DIV_FRAME_SIZE_XY, [58, 14] ],
            ],
        ],
    ],

    [ OBJECT_BOX,
        [ NAME, "divider panels without box rails" ],
        [ BOX_SIZE_XYZ, [62, 46, 22] ],
        [ BOX_NO_LID_B, true ],
        [ BOX_FEATURE,
            [ NAME, "rail disabled compartment" ],
            [ FTR_COMPARTMENT_SIZE_XYZ, [54, 38, 16] ],
            [ FTR_DIVIDERS,
                [ NAME, "rail disabled dividers" ],
                [ DIV_RAILS_B, false ],
                [ DIV_NUM_DIVIDERS, 2 ],
                [ DIV_THICKNESS, 1.0 ],
                [ DIV_TAB_TEXT, ["R0A", "R0B"] ],
                [ DIV_TAB_SIZE_XY, [14, 5] ],
                [ DIV_FRAME_NUM_COLUMNS, -1 ],
            ],
        ],
    ],
];

Make(data);
