// Test: Box-level labels on all sides — FRONT, BACK, LEFT, RIGHT, BOTTOM
include <boardgame_insert_toolkit_lib.4.scad>;

data = [
    [ G_PRINT_LID_B, false ],
    [ G_PRINT_BOX_B, true ],
    [ G_ISOLATED_PRINT_BOX, "" ],
    [ OBJECT_BOX,
        [ NAME, "all side labels" ],
        [ BOX_SIZE_XYZ, [50, 50, 20] ],
        [ LABEL,
            [ LBL_TEXT, "FRONT" ],
            [ LBL_SIZE, AUTO ],
            [ LBL_PLACEMENT, FRONT ],
        ],
        [ LABEL,
            [ LBL_TEXT, "BACK" ],
            [ LBL_SIZE, AUTO ],
            [ LBL_PLACEMENT, BACK ],
        ],
        [ LABEL,
            [ LBL_TEXT, "LEFT" ],
            [ LBL_SIZE, AUTO ],
            [ LBL_PLACEMENT, LEFT ],
        ],
        [ LABEL,
            [ LBL_TEXT, "RIGHT" ],
            [ LBL_SIZE, AUTO ],
            [ LBL_PLACEMENT, RIGHT ],
        ],
        [ LABEL,
            [ LBL_TEXT, "BOTTOM" ],
            [ LBL_SIZE, AUTO ],
            [ LBL_PLACEMENT, BOTTOM ],
        ],
        [ BOX_FEATURE,
            [ FTR_COMPARTMENT_SIZE_XYZ, [46, 46, 18] ],
        ],
    ],
];
Make(data);
