// Test: Physical validation messages for fit and printability issues
include <../../../release/lib/boardgame_insert_toolkit_lib.4.scad>;

data = [
    [ G_PRINT_LID_B, true ],
    [ G_PRINT_BOX_B, false ],
    [ G_ISOLATED_PRINT_BOX, "" ],
    [ OBJECT_BOX,
        [ NAME, "physical validation box" ],
        [ BOX_SIZE_XYZ, [50, 40, 12] ],
        [ BOX_NO_LID_B, true ],
        [ BOX_WALL_THICKNESS, 0.6 ],
        [ BOX_LID,
            [ LID_PATTERN_THICKNESS, 0.2 ],
            [ LID_FRAME_WIDTH, 0.2 ],
        ],
        [ BOX_FEATURE,
            [ NAME, "too tall and overlapping" ],
            [ FTR_COMPARTMENT_SIZE_XYZ, [30, 28, 12] ],
            [ POSITION_XY, [0, 0] ],
        ],
        [ BOX_FEATURE,
            [ NAME, "out of bounds and overlapping" ],
            [ FTR_COMPARTMENT_SIZE_XYZ, [30, 28, 8] ],
            [ POSITION_XY, [20, 0] ],
        ],
    ],
    [ OBJECT_DIVIDERS,
        [ NAME, "thin divider" ],
        [ DIV_THICKNESS, 0.2 ],
        [ DIV_FRAME_SIZE_XY, [20, 12] ],
        [ DIV_TAB_TEXT, ["A", "B"] ],
    ],
    [ OBJECT_BOX,
        [ NAME, "render target" ],
        [ BOX_SIZE_XYZ, [20, 20, 8] ],
        [ BOX_LID,
            [ LID_SOLID_B, true ],
        ],
        [ BOX_FEATURE,
            [ FTR_COMPARTMENT_SIZE_XYZ, [16, 16, 6] ],
        ],
    ],
];
Make(data);
